#+TITLE: my emacs config
#+AUTHOR: Anthony Rodriguez
#+EMAIL: anthony@nezia.dev
* initialization
** setup straight.el
   straight.el is an emacs package manager that makes it extremely convenient to
   install packages, pulling them automatically from (M)ELPA. It effectively
   replaces package.el completely, which is the reason why it is getting
   disabled in early-init.el.
#+BEGIN_SRC emacs-lisp
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+END_SRC

* packages installation
** install use-package and configure it to ensure packages per default
   use-package is a really nice emacs macro which allows us to configure emacs
   packages in a really clean, reproducible fashion. It is also integrated with
   straight.el, which means that we can configure it to ensure packages by
   default (if they are not downloaded, download it automatically).
#+BEGIN_SRC emacs-lisp
(straight-use-package 'use-package)
(use-package straight
             :custom (straight-use-package-by-default t))
#+END_SRC

** install no-littering to avoid cluttering ~/.emacs.d
   no-littering moves all generated emacs files in var and etc, which allows us
   to ignore those directories altogether since they are being generated by
   init.el. It allows the .emacs.d to stay clean and avoid committing generated
   files to version control.
#+BEGIN_SRC emacs-lisp
(use-package no-littering
  :config
  (require 'recentf)
  (add-to-list 'recentf-exclude no-littering-var-directory)
  (add-to-list 'recentf-exclude no-littering-etc-directory))
#+END_SRC

** install Nord theme
   Nord is the theme I use on all my environments, so having it in emacs is a no brainer.
   #+BEGIN_SRC emacs-lisp
    (add-to-list 'custom-theme-load-path (expand-file-name "~/.emacs.d/themes/"))
    (use-package nord-theme
    :init
    :config
    (load-theme 'nord t))
   #+END_SRC
** install evil mode to have vi bindings everywhere
   evil mode is a vi emulator for emacs, that also has bindings for a few
   plugins that we will use later (dired-sidebar and magit). 
#+BEGIN_SRC emacs-lisp
(use-package evil
  :init
  (setq evil-want-C-i-jump nil)
  (setq evil-want-keybinding nil)
  :config (evil-mode 1))

(use-package evil-collection
  :after evil
  :config(evil-collection-init))
#+END_SRC

** install dired-sidebar
   dired-sidebar is a nice little plugin that allows us to have a little
   toggleable sidebar on the side (really useful when you don't know the
   directory structure of your project too well, but it barely has any uses
   thanks to the next plugin we will be installing).
#+BEGIN_SRC emacs-lisp
(use-package vscode-icon)
(use-package dired-sidebar
    :commands (dired-sidebar-toggle-sidebar)
    :config
    (setq dired-sidebar-subtree-line-prefix "__")
    (setq dired-sidebar-theme 'vscode)
    (setq dired-sidebar-use-term-integration t)
    (setq dired-sidebar-use-custom-font t))
#+END_SRC
** install projectile
   projectile is a plugin that automatically binds directories to "projects",
   effectively allowing to leverage the power of fuzzy finding to be able to
   navigate project trees in a really efficient way.
#+BEGIN_SRC emacs-lisp
(use-package projectile
  :config
  (projectile-register-project-type 'npm '("package.json")
    :project-file "package.json"
    :compile "npm install"
    :test "npm test"
    :run "npm start"
    :test-suffix ".spec")
  (projectile-mode +1))
(defvar projectile-project-search-path '(("~/dev" . 3)))
#+END_SRC

** install magit
   magit is one of the best git interfaces I have ever used. It allows for
   keyboard driven git management, which is something that I haven't found on a
   lot of other text editors. It also works with vi bindings, thanks to evil mode.
#+BEGIN_SRC emacs-lisp
(use-package magit)
#+END_SRC

** install ivy (an emacs fuzzy finder that integrates into the mini buffer
   ivy is a fuzzy finder for emacs that integrates nicely in the mini buffer,
   effectively allowing all the typing to be fuzzy found, no matter what the
   source is: if it runs in the mini buffer, it will fuzzy find. Really useful
   for projectile, allowing us not to type the entire directory structure by hand.
    #+BEGIN_SRC emacs-lisp
    (use-package ivy
    :init
    (setq enable-recursive-minibuffers t)
    :config
    (ivy-mode))
    #+END_SRC

** install fira code mode
    fira code mode is a minor mode that turns on ligatures for fira code in emacs.
    #+BEGIN_SRC emacs-lisp
	(use-package fira-code-mode
	:hook prog-mode)
    #+END_SRC
** install Flycheck
   Flycheck is a modern replacement for flymake, a base emacs plugin that allows
   us to get on-the-fly spell checking for a lot of different languages.
   #+BEGIN_SRC emacs-lisp
    (use-package flycheck
    :config
    (setq-default flycheck-disabled-checkers '(emacs-lisp-checkdoc)))
    

   #+END_SRC
*** enables Flycheck mode in programming mode
    This adds a hook to prog mode, enabling Flycheck on every source code file.
    #+BEGIN_SRC emacs-lisp
    (add-hook 'prog-mode-hook 'flycheck-mode)
    #+END_SRC

* bindings
** install general (a more convenient keybindings manager)
   general is a replacement for the default emacs keybind macros, allowing us to
   write keybinds in a more concise and readable manner.
    #+BEGIN_SRC emacs-lisp
    (use-package general)
    #+END_SRC

** bindings for C-x
    #+BEGIN_SRC emacs-lisp
    (general-define-key 
    :states 'normal
    :prefix "C-x"
    "p" 'projectile-command-map
    "g" 'magit)

    #+END_SRC

** bindings for SPC
    #+BEGIN_SRC emacs-lisp
    (general-define-key 
    :states 'normal
    :prefix "SPC"
    "t" 'dired-sidebar-toggle-sidebar)
    #+END_SRC
* miscellanous configuration
 This section contains different settings that aren't related to packages or
 initialization, such as fonts and other (really) useful things. 
** sets the font to Fira Code
   Fira Code has been my favorite font since I first found out about it: it's
   very readable and also has ligatures, which is a feature not a lot of fonts
   have, and I feel like it really helps to make my code a lot more readable.
   #+BEGIN_SRC emacs-lisp
    (set-face-attribute 'default nil :font "Fira Code")
   #+END_SRC

** makes the emacs startup minimal (remove all startup messages and splashscreens)
   Disables the startup messages and splash screens you would get on startup.
    #+BEGIN_SRC emacs-lisp
    (setq inhibit-startup-message t)
    (setq inhibit-splash-screen t)
    (setq initial-scratch-message nil)
    #+END_SRC
** disable toolbars / scroll bars
   Disables the toolbars and scrollbars because I don't use them at all.
   #+BEGIN_SRC emacs-lisp
    (tool-bar-mode -1)
    (menu-bar-mode -1)
    (if (boundp 'fringe-mode)
    (fringe-mode -1))
    (if (boundp 'scroll-bar-mode)
	(scroll-bar-mode -1))
   #+END_SRC

** disable bell (visual and audio)
   Disables the annoying visual and audio bell.
   #+BEGIN_SRC emacs-lisp
    (setq ring-bell-function 'ignore)
   #+END_SRC

** enable relative line numbers in programming mode
   This adds a hook to prog mode to enable relative line numbers in source code files.
   #+BEGIN_SRC emacs-lisp
    (setq display-line-numbers-type 'relative)
    (add-hook 'prog-mode-hook 'display-line-numbers-mode)
   #+END_SRC

** enables fill-column for org mode
   This effectively limits the maximum amount of characters per line to 80,
   which makes it really convenient when you're editing org mode files.  
   #+BEGIN_SRC emacs-lisp
   (add-hook 'org-mode-hook '(lambda () (setq fill-column 80)))
   (add-hook 'org-mode-hook 'auto-fill-mode)
   #+END_SRC
