#+TITLE: my emacs config
#+AUTHOR: Anthony Rodriguez
#+EMAIL: anthony@nezia.dev
* initialization
** setup MELPA
    MELPA is an emacs package repository that contains a lot of community
    packages.
    #+begin_src emacs-lisp
	(require 'package)
	(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
	(package-initialize)
    #+end_src
** setup use-package
   use-package is an emacs package manager that makes it extremely convenient to
   install packages, pulling them automatically from (M)ELPA. It effectively
   replaces package.el completely, which is the reason why it is getting
   disabled in early-init.el.
    #+begin_src emacs-lisp
    	(unless (package-installed-p 'use-package)
		(package-refresh-contents)
		(package-install 'use-package))
	(require 'use-package)
	(require 'use-package-ensure)
	(setq use-package-always-ensure t)
    #+end_src

* packages installation
** install no-littering to avoid cluttering ~/.emacs.d
   no-littering moves all generated emacs files in var and etc, which allows us
   to ignore those directories altogether since they are being generated by
   init.el. It allows the .emacs.d to stay clean and avoid committing generated
   files to version control.
#+begin_src emacs-lisp
(use-package no-littering
  :config
  (require 'recentf)
  (add-to-list 'recentf-exclude no-littering-var-directory)
  (add-to-list 'recentf-exclude no-littering-etc-directory))
#+end_src

** install Nord theme
   Nord is the theme I use on all my environments, so having it in emacs is a no brainer.
   #+begin_src emacs-lisp
    (add-to-list 'custom-theme-load-path (expand-file-name "~/.emacs.d/themes/"))
    (use-package nord-theme
    :init
    :config
    (load-theme 'nord t))
   #+end_src
** install doom-modeline
    doom-modeline is a replacement for the default emacs modeline, that allows us to
    have a nicer and more minimal looking modeline.
*** install all the icons
    we need all-the-icons to display the necessary icons in the doom-modeline bar.
    #+begin_src emacs-lisp
	(use-package all-the-icons)
    #+end_src
*** install doom-modeline itself
    #+begin_src emacs-lisp
	(use-package doom-modeline
	:init (doom-modeline-mode 1))
    #+end_src

** install evil mode to have vi bindings everywhere
   evil mode is a vi emulator for emacs, that also has bindings for a few
   plugins that we will use later (dired-sidebar and magit). 
#+begin_src emacs-lisp
(use-package evil
  :init
  (setq evil-want-C-i-jump nil)
  (setq evil-want-keybinding nil)
  :config (evil-mode 1))

(use-package evil-collection
  :after evil
  :config(evil-collection-init))
#+end_src

** install dired-sidebar
   dired-sidebar is a nice little plugin that allows us to have a little
   toggleable sidebar on the side (really useful when you don't know the
   directory structure of your project too well, but it barely has any uses
   thanks to the next plugin we will be installing).
#+begin_src emacs-lisp
(use-package vscode-icon)
(use-package dired-sidebar
    :commands (dired-sidebar-toggle-sidebar)
    :config
    (setq dired-sidebar-subtree-line-prefix "__")
    (setq dired-sidebar-theme 'vscode)
    (setq dired-sidebar-use-term-integration t)
    (setq dired-sidebar-use-custom-font t))
#+end_src

** install projectile
   projectile is a plugin that automatically binds directories to "projects",
   effectively allowing to leverage the power of fuzzy finding to be able to
   navigate project trees in a really efficient way.
#+begin_src emacs-lisp
  (use-package projectile
    :init
    (setq projectile-project-search-path '(("~/dev" . 3)))
    :config
    (projectile-register-project-type 'npm '("package.json")
      :project-file "package.json"
      :compile "npm install"
      :test "npm test"
      :run "npm start"
      :test-suffix ".spec")
    (projectile-mode +1))
#+end_src

** install magit
   magit is one of the best git interfaces I have ever used. It allows for
   keyboard driven git management, which is something that I haven't found on a
   lot of other text editors. It also works with vi bindings, thanks to evil mode.
#+begin_src emacs-lisp
(use-package magit)
#+end_src

** install ivy (an emacs fuzzy finder that integrates into the mini buffer
    ivy is a fuzzy finder for emacs that integrates nicely in the mini buffer,
    effectively allowing all the typing to be fuzzy found, no matter what the
    source is: if it runs in the mini buffer, it will fuzzy find. Really useful
    for projectile, allowing us not to type the entire directory structure by hand.
    #+begin_src emacs-lisp
	(use-package ivy
	:config (ivy-mode 1))
#+end_src

** install org bullets
org-bullets is a nice little package that allows us to have pretty UTF-8 bullets
in org mode.
#+begin_src emacs-lisp
    (use-package org-bullets
    :hook org-mode)
#+end_src
** install Flycheck
   Flycheck is a modern replacement for flymake, a base emacs plugin that allows
   us to get on-the-fly spell checking for a lot of different languages.
   #+begin_src emacs-lisp
    (use-package flycheck
    :config
    (setq-default flycheck-disabled-checkers '(emacs-lisp-checkdoc)))
    #+end_src
*** enables Flycheck mode in programming mode
    This adds a hook to prog mode, enabling Flycheck on every source code file.
    #+begin_src emacs-lisp
    (add-hook 'prog-mode-hook 'flycheck-mode)
    #+end_src
** install which-key
which-key is a package that allows us to see what keybind we're typing after
waiting for a fixed duration (1 second by default).
#+begin_src emacs-lisp
  (use-package which-key
  :config
  (setq which-key-idle-delay 1)
  (which-key-mode))
#+end_src
** install web mode
#+begin_src emacs-lisp 
	      (use-package web-mode
		:mode
		("\\.php$" . web-mode)
		("\\.html$" . web-mode)
		("\\.jsx?$" . web-mode)
		("\\.tsx?$" . web-mode))
#+end_src
** install LSP Mode
    #+begin_src emacs-lisp
      (use-package lsp-mode
	:ensure lsp-ui
	:init
	(setq lsp-keymap-prefix "C-x l")
	(setq lsp-ui-doc-show-with-mouse nil)
	(setq lsp-ui-doc-show-with-cursor nil)
	(setq lsp-ui-doc-position 'bottom)
	:hook ((prog-mode . lsp)
	       (vue-mode . lsp)
	       (lsp-mode . lsp-enable-which-key-integration)))
    #+end_src
*** format code on save
#+begin_src emacs-lisp
  (add-hook 'before-save-hook 'lsp-format-buffer nil )
#+end_src
*** install lsp ivy integration
    #+begin_src emacs-lisp
      (use-package lsp-ivy :commands lsp-ivy-workspace-symbol)
    #+end_src
*** install company
#+begin_src emacs-lisp
  (use-package company)
#+end_src
*** install yasnippet
#+begin_src emacs-lisp
  (use-package yasnippet
    :ensure yasnippet-snippets
    :config
    (yas-reload-all)
    :hook ((prog-mode . yas-minor-mode)
	   (web-mode . yas-minor-mode)))
#+end_src
*** install vue mode
    #+begin_src emacs-lisp
      (use-package vue-mode
	:config (setq mmm-submode-decoration-level 0)
      :hook (mmm-mode . (lambda () (set-face-background 'mmm-default-submode-face nil)))
	:mode "\\.vue$"
	)
    #+end_src
* bindings
** install general (a more convenient keybindings manager)
   general is a replacement for the default emacs keybind macros, allowing us to
   write keybinds in a more concise and readable manner.
    #+begin_src emacs-lisp
    (use-package general)
    #+end_src
    
** bindings for C-x
    These bindings are bindings that are supposed to do something no matter what the
    mode is (global keybindings).
    #+begin_src emacs-lisp
	  (general-define-key 
	  :states 'normal
	  :prefix "C-x"
	  "p" 'projectile-command-map
	  "g" 'magit)

    #+end_src
** bindings for C-c
    These bindings are bindings that are for my own convenience (personal keybindings).
    #+begin_src emacs-lisp
	  (general-define-key 
	  :states 'normal
	  :prefix "C-c"
	  "t" 'dired-sidebar-toggle-sidebar
	  "d" 'lsp-ui-doc-glance)
    #+end_src
* miscellanous configuration
 This section contains different settings that aren't related to packages or
 initialization, such as fonts and other (really) useful things. 
** sets the font to Fira Code
   Fira Code has been my favorite font since I first found out about it: it's
   very readable and also has ligatures, which is a feature not a lot of fonts
   have, and I feel like it really helps to make my code a lot more readable.
   #+begin_src emacs-lisp
    (set-face-attribute 'default nil :font "Fira Code 12")
   #+end_src

** makes the emacs startup minimal (remove all startup messages and splashscreens)
   Disables the startup messages and splash screens you would get on startup.
    #+begin_src emacs-lisp
    (setq inhibit-startup-message t)
    (setq inhibit-splash-screen t)
    (setq initial-scratch-message nil)
    #+end_src
** disable toolbars / scroll bars
   Disables the toolbars and scrollbars because I don't use them at all.
   #+begin_src emacs-lisp
    (tool-bar-mode -1)
    (menu-bar-mode -1)
    (if (boundp 'fringe-mode)
    (fringe-mode -1))
    (if (boundp 'scroll-bar-mode)
	(scroll-bar-mode -1))
   #+end_src

** disable bell (visual and audio)
   Disables the annoying visual and audio bell.
   #+begin_src emacs-lisp
    (setq ring-bell-function 'ignore)
   #+end_src

** disable relative line numbers in some modes
   This adds a hook to some modes that don't really need line numbers to disable them.
   #+begin_src emacs-lisp
     (dolist (mode '(org-mode-hook
     term-mode-hook
     shell-mode-hook
     eshell-mode-hook))
     (add-hook mode (lambda () (display-line-numbers-mode 0))))
   #+end_src

** enables fill-column for org mode
   This effectively limits the maximum amount of characters per line to 80,
   which makes it really convenient when you're editing org mode files.  
   #+begin_src emacs-lisp
   (add-hook 'org-mode-hook '(lambda () (setq fill-column 80)))
   (add-hook 'org-mode-hook 'auto-fill-mode)
   #+end_src
** enable matching parenthesis / brackets / quotes
    This is just so that emacs automatically pairs characters when typing in
    prog-mode or web-mode.
    #+begin_src emacs-lisp
    (add-hook 'prog-mode-hook 'electric-pair-mode)
    (add-hook 'web-mode-hook 'electric-pair-mode)
    #+end_src
